name: vite static build

on:
  workflow_dispatch:
  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "commit_msg=`git log -1 --format=format:%s`" >> $GITHUB_ENV
          echo "origin_url=`git remote get-url origin`" >> $GITHUB_ENV
          npm ci
          npm run build
          cd dist
          git config user.name github-actions
          git config user.email github-actions@github.com
          git init
          git add -A
          git commit -m "${{ env.commit_msg }}"
          git push -f "${{ env.origin_url }}" main:gh-pages

      # - uses: actions/upload-artifact@v2
      #   with: { name: static-build, path: docs }
